markdown: kramdown
# remote_theme: just-the-docs/just-the-docs
theme: just-the-docs
color_scheme: dark

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
compress_html:
  ignore:
    envs: all

baseurl: /docs
source: .
destination: ./../_docs
permalink: pretty

enable_copy_code_button: true

# Jekyll SEO
title: "MTRGen Docs"
tagline: "PHP file generator"
description: "Generate files from templates with ease."
author:
  name: Matronator
  url: https://matronator.cz
logo: "assets/images/logo-main.png"
social:
  name: matronator
  links:
    - https://github.com/matronator
    - https://www.linkedin.com/in/matronator

# Navigation
aux_links:
  "View on GitHub":
    "//github.com/matronator/MTRGen"
  "Main website":
    "//mtrgen.matronator.cz"
heading_anchors: true

nav_external_links:
  - title: "Main website"
    url: "https://mtrgen.matronator.cz"
  - title: "View on GitHub"
    url: "https://github.com/matronator/MTRGen"

# Callouts
callouts_opacity: 0.35
callouts:
  warning:
    title: Warning
    color: red
  info:
    title: Info
    color: blue
  tip:
    title: Tip
    color: green
  caution:
    title: Caution
    color: yellow
  note:
    title: Note
    color: purple
